extends Node

signal on_开始游戏()
signal on_继续游戏()
signal on_游戏设置()
signal on_游戏模组()
signal on_游戏结束()

signal on_创建角色()
signal on_生成世界()
signal on_生成妖兽()
signal on_生成门派()
signal on_生成城镇()
signal on_生成人物()
signal on_生成关系()
signal on_进入世界()

signal on_显示地形()
signal on_显示据点()
signal on_显示事件()
signal on_显示日期()
signal on_玩家回合()
signal on_电脑回合()

signal on_物体载入(obj)
signal on_创建玩家()
signal on_物体回合()
signal on_移动(obj,dir)

signal on_物体移动(from,to)

signal on_玩家出现()
signal on_玩家活着()
signal on_玩家死亡()
signal on_玩家打坐()
signal on_玩家移动(dir)
signal on_玩家推动(dir)
signal on_玩家攻击(dir)
signal on_玩家躲闪(dir)
signal on_玩家招架(dir)
signal on_玩家受伤(dir)
signal on_玩家调查(dir)
signal on_玩家拾取(dir)
signal on_玩家放置(obj,dir)
signal on_玩家操作(dir)
signal on_玩家对话(dir)
signal on_玩家使用(obj,dir)
signal on_玩家投掷(obj,dir)

signal on_打开人物页面()
signal on_打开功法页面()
signal on_打开物品页面()
signal on_打开关系页面()
signal on_打开门派页面()

signal on_开始画符()
signal on_选择符文()
signal on_选择灵纸()
signal on_选择灵墨()
signal on_选择灵笔()
signal on_控制笔法()
signal on_符文注灵()
signal on_符文绘成()

signal on_开始炼丹()
signal on_选择丹方()
signal on_选择主药()
signal on_选择辅药()
signal on_选择药引()
signal on_控制炉火()
signal on_凝结成丹()
signal on_灵丹出炉()

signal on_开始炼器()
signal on_选择图纸()
signal on_选择主体()
signal on_选择客体()
signal on_选择配饰()
signal on_开始炼制()
signal on_炼制成型()
signal on_法器出炉()

signal on_开始布阵()
signal on_选择阵图()
signal on_选择阵眼()
signal on_选择压阵()
signal on_选择辅阵()
signal on_放置灵石()
signal on_开启阵法()
signal on_关闭阵法()
signal on_触发阵法()
signal on_攻击阵法()
signal on_攻击阵眼()
signal on_破坏阵法()
signal on_拆解阵法()

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.
